import '../globals.css'
import type { Metadata } from 'next'
import { Header } from '@/components/header'
import { CartContextProvider } from '@/context/CartProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body className="bg-background max-w-[1120px] mx-auto min-h-screen antialiased">
        <CartContextProvider>
          <Header />
          {children}
        </CartContextProvider>
      </body>
    </html>
  )
}
